---
- hosts: all
  become: True
  tasks:
    - name: update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: install required applications
      yum:
        name: "{{ item }}"
        state: latest
      loop: '{{ packages_to_install }}'

    - name: start Docker engine service
      tags: start_docker_service
      service:
        name: docker
        state: started  

    - name: create a welcome message
      template:
        src: ~/ProjectEnhancement/AnsibleTASK/templates/welcome_msg.j2
        dest: /etc/profile.d/welcome_msg.sh
        owner: root
        group: root
        mode: '0644'

- hosts: jenkins
  become: True
  tasks:
    - name: install jenkins
      ansible.builtin.command:
        cmd: docker run -d -p 8080:8080 -p 50000:50000 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkins/jenkins

         




