---
- hosts: all
  become: True
  tasks:
    - name: update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: install required applications
      yum:
        name: "{{ item }}"
        state: latest
      loop: '{{ packages_to_install }}'

    - name: start Docker engine service
      tags: start_docker_service
      service:
        name: docker
        state: started  

    - name: create a welcome message
      template:
        src: ~/ProjectEnhancement/AnsibleTASK/templates/welcome_msg.j2
        dest: /etc/profile.d/welcome_msg.sh
        owner: root
        group: root
        mode: '0644'

- hosts: jenkins
  become: True
  tasks:
    - name: install jenkins
      ansible.builtin.command:
        cmd: docker run -p 8081:8080 -p 50000:50000 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkins/jenkins

    # - name: Ensure group "sudo" exists
    #   ansible.builtin.group:
    #     name: sudo
    #     state: present

    # - name: add jenkins user
    #   ansible.builtin.user:
    #     name: jenkins
    #     comment: jenkins
    #     group: sudo

    # - name: Create a 2048-bit SSH key for user jenkins in ~jenkins/.ssh/id_rsa.pub
    #   ansible.builtin.user:
    #     name: jenkins
    #     generate_ssh_key: yes
    #     ssh_key_bits: 2048
    #     ssh_key_file: .ssh/id_rsa

    # - name: download jenkins.repo
    #   get_url:   
    #     url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    #     dest: /etc/yum.repos.d/jenkins.repo

    # - name: import jenkins key
    #   rpm_key: 
    #     state: present
    #     key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    # - name: install jenkins
    #   yum: 
    #     name: jenkins
    #     state: present

    # - name: start & enable jenkins
    #   systemd:
    #     name: jenkins
    #     state: started   
    #     enabled: true

    # - name: sleep for 30 seconds and continue with play
    #   wait_for: timeout=30
    #   delegate_to: localhost

    # - name: init password jenkin
    #   shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    #   changed_when: false
    #   register: result

    # - name: print init password jenkins
    #   debug:
    #     var: result.stdout
         




