---
- hosts: all
  become: True
  tasks:
    - name: update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: install required applications
      yum:
        name: "{{ item }}"
        state: latest
      loop: '{{ packages_to_install }}'

    - name: start Docker engine service
      tags: start_docker_service
      service:
        name: docker
        state: started

    - name: create a welcome message
      template:
        src: /home/ansible/ProjectEnhancement/AnsibleTASK/templates/welcome_msg.j2
        dest: /etc/profile.d/welcome_msg.sh
        owner: root
        group: root
        mode: '0644'

- hosts: tag_Name_jenkins_server
  become: True
  tasks:
    - name: copy jenkinsImage Dockerfile
      template:
        src: /home/ansible/ProjectEnhancement/AnsibleTASK/jenkinsImage/Dockerfile
        dest: /home/ansible/Dockerfile
        owner: root
        group: root
        mode: '0644'

    - name: copy jenkinsImage plugins file
      template:
        src: /home/ansible/ProjectEnhancement/AnsibleTASK/jenkinsImage/jenkins_plugins.txt
        dest: /home/ansible/jenkins_plugins.txt
        owner: root
        group: root
        mode: '0644'

    - name: build jenkins image
      ansible.builtin.command:
        cmd: docker build -t jenkins-blickng:latest .

    - name: run jenkins image
      ansible.builtin.command:
        cmd: docker run -d -p 8080:8080 jenkins-blickng

    - name: install jenkins
      ansible.builtin.command:
        cmd: docker run -d -p 8081:8080 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkins/jenkins
        

         




